package cpsc326;

enum TokenType {
    AND, OR, ELSE, FALSE, FOR, FUN,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, SEMICOLON,
    PLUS, MINUS, STAR, SLASH,
    STRING, NUMBER, IDENTIFIER,
    IF, NIL, PRINT, RETURN,
    STRUCT, THIS, TRUE, VAR, WHILE,
    EOF
}